spring:
  application:
    name: @project.artifactId@
  main:
    web-application-type: none
    banner-mode: off
logging:
  file:
    name: mcp-server.log
    path: ./catalog
        #ai:
   # mcp:
    #  server:
     #   name: @project.artifactId@
      #  version: @project.version@
        #sse-message-endpoint: /mcp/message
       # sse-endpoint: /sse
        #type: sync
